#!/bin/bash.exe

function GetPid() {
  for i in `ps -ef|grep XWin|awk '{print $2}'`;do if grep -E -q "$1|${1%%.*}" /proc/$i/cmdline;then echo "$i";fi;done
}

XPID="`GetPid "$DISPLAY"`"
if [ -n "$XPID" ]; then
  kill -TERM $XPID
fi
