#!/bin/bash

#APPLET="`basename "$0"`"
APPLET="$1"

if [ "$APPLET" == "MobaControlUsers" ]; then
  control userpasswords2
elif [ "$APPLET" == "MobaControlFolders" ]; then
  control folders
elif [ "$APPLET" == "MobaControlDisplay" ]; then
  control desktop
elif [ "$APPLET" == "MobaControlPrinters" ]; then
  control printers
elif [ "$APPLET" == "MobaControlMouse" ]; then
  control mouse
elif [ "$APPLET" == "MobaControlKeyboard" ]; then
  control keyboard
elif [ "$APPLET" == "MobaControlNetwork" ]; then
  control netconnections
elif [ "$APPLET" == "MobaControlColors" ]; then
  control color
elif [ "$APPLET" == "MobaControlTime" ]; then
  control date/time
elif [ "$APPLET" == "MobaControlScheduler" ]; then
  control schedtasks
elif [ "$APPLET" == "MobaControlAdminTools" ]; then
  control admintools
elif [ "$APPLET" == "MobaControlTelephony" ]; then
  control telephony
elif [ "$APPLET" == "MobaControlFonts" ]; then
  control fonts
elif [ "$APPLET" == "MobaControlInternational" ]; then
  control international
elif [ "$APPLET" == "MobaControlComputer" ]; then
  cygstart compmgmt.msc
elif [ "$APPLET" == "MobaControlEvents" ]; then
  cygstart eventvwr.msc
elif [ "$APPLET" == "MobaControlDevices" ]; then
  cygstart devmgmt.msc
elif [ "$APPLET" == "MobaControlServices" ]; then
  cygstart services.msc
elif [ "$APPLET" == "MobaControlDefrag" ]; then
  cygstart dfrg.msc
elif [ "$APPLET" == "MobaControlDisks" ]; then
  cygstart diskmgmt.msc
elif [ "$APPLET" == "MobaControlSecurity" ]; then
  cygstart secpol.msc
elif [ "$APPLET" == "MobaControlPolicies" ]; then
  cygstart gpedit.msc
elif [ "$APPLET" == "MobaControlRegistry" ]; then
  regedit
elif [ "$APPLET" == "MobaControlRestore" ]; then
  rstrui
elif [ "$APPLET" == "MobaControlStartup" ]; then
  msconfig
elif [ "$APPLET" == "MobaControlDirectX" ]; then
  dxdiag
elif [ "$APPLET" == "MobaControlTasks" ]; then
  taskmgr
elif [ "$APPLET" == "MobaControlAccessibility" ]; then
  cygstart access.cpl
elif [ "$APPLET" == "MobaControlNewDevice" ]; then
  cygstart hdwwiz.cpl
elif [ "$APPLET" == "MobaControlPrograms" ]; then
  cygstart appwiz.cpl
elif [ "$APPLET" == "MobaControlUpdates" ]; then
  cygstart wuaucpl.cpl
elif [ "$APPLET" == "MobaControlCertificates" ]; then
  cygstart certmgr.msc
elif [ "$APPLET" == "MobaControlCheckDisks" ]; then
  chkdsk
elif [ "$APPLET" == "MobaControlDCom" ]; then
  dcomcnfg
elif [ "$APPLET" == "MobaControlClean" ]; then
  cleanmgr
elif [ "$APPLET" == "MobaControlSignature" ]; then
  sigverif
elif [ "$APPLET" == "MobaControlInternet" ]; then
  cygstart inetcpl.cpl
elif [ "$APPLET" == "MobaControlUsersAdvanced" ]; then
  cygstart lusrmgr.msc
elif [ "$APPLET" == "MobaControlOdbc" ]; then
  cygstart odbccp32.cpl
elif [ "$APPLET" == "MobaControlPerformances" ]; then
  cygstart perfmon.msc
elif [ "$APPLET" == "MobaControlShares" ]; then
  cygstart fsmgmt.msc
elif [ "$APPLET" == "MobaControlAudio" ]; then
  cygstart mmsys.cpl
elif [ "$APPLET" == "MobaControlCheckSystemFiles" ]; then
  sfc /scannow
elif [ "$APPLET" == "MobaControlSystemFiles" ]; then
  sysedit
elif [ "$APPLET" == "MobaControlSystem" ]; then
  cygstart sysdm.cpl
elif [ "$APPLET" == "MobaControlFirewall" ]; then
  cygstart firewall.cpl
elif [ "$APPLET" == "MobaControlAudioVolume" ]; then
  sndvol
elif [ "$APPLET" == "MobaControlWindowsVersion" ]; then
  winver
elif [ "$APPLET" == "MobaControlDriversList" ]; then
  driverquery
else
  control
fi


