#!/bin/bash.exe

_tob() {
  if [ -e "/bin/$1.exe" ]; then
    _p="/bin/$1.exe"
    shift
    if [ "$_p" = "/bin/grep.exe" ]; then
      "$_p" --colour "$@"
    else
      "$_p" "$@"
    fi
  elif [ -e "/bin/$1" ]; then
    "$@"
  else
    if [ -e "/bin/busybox.exe" ]; then
      tbcmd="\n`/bin/busybox.exe --list`\n"
      if [ "${tbcmd#*
$1
*}" != "${tbcmd}" ]; then
        /bin/busybox.exe "$@"
        return
      fi
    fi
    if [ -e "/bin/toybox.exe" ]; then
      tbcmd="\n`/bin/toybox.exe`\n"
      if [ "${tbcmd#*
$1
*}" != "${tbcmd}" ]; then
        /bin/toybox.exe "$@"
        return
      fi
    fi
  fi
}
_bbf() {
  if [ -e "/bin/$1.exe" ]; then
    _p="/bin/$1.exe"
    shift
    "$_p" "$@"
  elif [ -e "/bin/$1" ]; then
    "$@"
  else
    /bin/busybox.exe "$@"
  fi
}
_tbf() {
  if [ -e "/bin/$1.exe" ]; then
    _p="/bin/$1.exe"
    shift
    "$_p" "$@"
  elif [ -e "/bin/$1" ]; then
    "$@"
  else
    /bin/toybox.exe "$@"
  fi
}

alias cls='echo -e "\ec\e[3J"'
alias clearall='echo -e "\ec\e[3J"'

alias "compress"="_tbf compress"
alias "count"="_tbf count"
alias "factor"="_tbf factor"
alias "free"="_tbf free"
alias "host"="_tbf host"
alias "link"="_tbf link"
alias "nc"="_tbf nc"
alias "netcat"="_tbf netcat"
alias "nl"="_tbf nl"
alias "shred"="_tbf shred"
alias "truncate"="_tbf truncate"
alias "uptime"="_tbf uptime"

export VAGRANT_DETECTED_OS="cygwin"
export GIT_PAGER="/bin/busybox.exe less -R"

alias "ar"="_bbf ar"
alias "awk"="_bbf awk"
alias "base64"="_bbf base64"
alias "basename"="_bbf basename"
alias "bunzip2"="_bbf bunzip2"
alias "bzcat"="_bbf bzcat"
alias "bzip2"="_bbf bzip2"
alias "cal"="_bbf cal"
alias "cat"="_bbf cat"
alias "catv"="_bbf catv"
alias "chat"="_bbf chat"
alias "chgrp"="_bbf chgrp"
alias "chmod"="_bbf chmod"
alias "chown"="_bbf chown"
alias "chpasswd"="_bbf chpasswd"
alias "chpst"="_bbf chpst"
alias "chroot"="_bbf chroot"
alias "chrt"="_bbf chrt"
alias "cksum"="_bbf cksum"
alias "clear"="_bbf clear"
alias "cmp"="_bbf cmp"
alias "comm"="_bbf comm"
alias "cp"="_bbf cp"
alias "cpio"="_bbf cpio"
alias "crond"="_bbf crond"
alias "crontab"="_bbf crontab"
alias "cryptpw"="_bbf cryptpw"
alias "cut"="_bbf cut"
alias "date"="_bbf date"
alias "dc"="_bbf dc"
alias "dd"="_bbf dd"
alias "devmem"="_bbf devmem"
alias "df"="_bbf df"
alias "diff"="_bbf diff"
alias "dirname"="_bbf dirname"
alias "dnsd"="_bbf dnsd"
alias "dnsdomainname"="_bbf dnsdomainname"
alias "dos2unix"="_bbf dos2unix"
alias "du"="_bbf du"
alias "ed"="_bbf ed"
alias "env"="_bbf env"
alias "envdir"="_bbf envdir"
alias "envuidgid"="_bbf envuidgid"
alias "expand"="_bbf expand"
alias "expr"="_bbf expr"
alias "fakeidentd"="_bbf fakeidentd"
alias "find"="_bbf find"
alias "fold"="_bbf fold"
alias "fsync"="_bbf fsync"
alias "ftpget"="_bbf ftpget"
alias "ftpput"="_bbf ftpput"
alias "fuser"="_bbf fuser"
alias "gawk"="_bbf awk"
alias "getopt"="_bbf getopt"
alias "groups"="_bbf groups"
alias "gunzip"="_bbf gunzip"
alias "gzip"="_bbf gzip"
alias "hd"="_bbf hd"
alias "head"="_bbf head"
alias "hexdump"="_bbf hexdump"
alias "hostid"="_bbf hostid"
alias "hostname"="_bbf hostname"
alias "httpd"="_bbf httpd"
alias "id"="_bbf id"
alias "inetd"="_bbf inetd"
alias "install"="_bbf install"
alias "iostat"="_bbf iostat"
alias "ipcalc"="_bbf ipcalc"
alias "killall"="_bbf killall"
alias "killall5"="_bbf killall5"
alias "less"="_bbf less"
alias "ln"="_bbf ln"
alias "logger"="_bbf logger"
alias "logname"="_bbf logname"
alias "logread"="_bbf logread"
alias "lpd"="_bbf lpd"
alias "lpq"="_bbf lpq"
alias "lpr"="_bbf lpr"
alias "ls"="_bbf ls --color=auto"
alias "lsof"="_bbf lsof"
alias "lzcat"="_bbf lzcat"
alias "lzma"="_bbf lzma"
alias "lzop"="_bbf lzop"
alias "lzopcat"="_bbf lzopcat"
alias "makemime"="_bbf makemime"
alias "md5sum"="_bbf md5sum"
alias "mesg"="_bbf mesg"
alias "mkdir"="_bbf mkdir"
alias "mkfifo"="_bbf mkfifo"
alias "mknod"="_bbf mknod"
alias "mktemp"="_bbf mktemp"
alias "more"="_bbf more"
alias "mpstat"="_bbf mpstat"
alias "mt"="_bbf mt"
alias "mv"="_bbf mv"
alias "nice"="_bbf nice"
alias "nmeter"="_bbf nmeter"
alias "nohup"="_bbf nohup"
alias "nslookup"="_bbf nslookup"
alias "od"="_bbf od"
alias "patch"="_bbf patch"
alias "pgrep"="_bbf pgrep"
alias "pidof"="_bbf pidof"
alias "pipe_progress"="_bbf pipe_progress"
alias "pkill"="_bbf pkill"
alias "popmaildir"="_bbf popmaildir"
alias "printenv"="_bbf printenv"
alias "pscan"="_bbf pscan"
alias "pstree"="_bbf pstree"
alias "pwdx"="_bbf pwdx"
alias "readlink"="_bbf readlink"
alias "realpath"="_bbf realpath"
alias "reformime"="_bbf reformime"
alias "renice"="_bbf renice"
alias "reset"="_bbf reset"
alias "resize"="_bbf resize"
alias "rev"="_bbf rev"
alias "rm"="_bbf rm"
alias "rmdir"="_bbf rmdir"
alias "rpm"="_bbf rpm"
alias "rpm2cpio"="_bbf rpm2cpio"
alias "run-parts"="_bbf run-parts"
alias "runsv"="_bbf runsv"
alias "runsvdir"="_bbf runsvdir"
alias "script"="_bbf script"
alias "script"="_bbf scriptreplay"
alias "sed"="_bbf sed"
alias "sendmail"="_bbf sendmail"
alias "seq"="_bbf seq"
alias "setsid"="_bbf setsid"
alias "setuidgid"="_bbf setuidgid"
alias "sha1sum"="_bbf sha1sum"
alias "sha256sum"="_bbf sha256sum"
alias "sha3sum"="_bbf sha3sum"
alias "sha512sum"="_bbf sha512sum"
alias "sleep"="_bbf sleep"
alias "smemcap"="_bbf smemcap"
alias "softlimit"="_bbf softlimit"
alias "sort"="_bbf sort"
alias "split"="_bbf split"
alias "start-stop-daemon"="_bbf start-stop-daemon"
alias "stat"="_bbf stat"
alias "strings"="_bbf strings"
alias "stty"="_bbf stty"
alias "sum"="_bbf sum"
alias "sv"="_bbf sv"
alias "svlogd"="_bbf svlogd"
alias "sync"="_bbf sync"
alias "sysctl"="_bbf sysctl"
alias "syslogd"="_bbf syslogd"
alias "tac"="_bbf tac"
alias "tail"="_bbf tail"
alias "tar"="_bbf tar"
alias "tcpsvd"="_bbf tcpsvd"
alias "tee"="_bbf tee"
alias "tftp"="_bbf tftp"
alias "tftpd"="_bbf tftpd"
alias "time"="_bbf time"
alias "timeout"="_bbf timeout"
alias "touch"="_bbf touch"
alias "tr"="_bbf tr"
alias "tty"="_bbf tty"
alias "ttysize"="_bbf ttysize"
alias "udpsvd"="_bbf udpsvd"
alias "uname"="_bbf uname"
alias "uncompress"="_bbf uncompress"
alias "unexpand"="_bbf unexpand"
alias "uniq"="_bbf uniq"
alias "unix2dos"="_bbf unix2dos"
alias "unlzma"="_bbf unlzma"
alias "unlzop"="_bbf unlzop"
alias "unxz"="_bbf unxz"
alias "unzip"="_bbf unzip"
alias "usleep"="_bbf usleep"
alias "uudecode"="_bbf uudecode"
alias "uuencode"="_bbf uuencode"
alias "vlock"="_bbf vlock"
alias "volname"="_bbf volname"
alias "watch"="_bbf watch"
alias "wc"="_bbf wc"
alias "which"="_bbf which"
alias "whoami"="_bbf whoami"
alias "xargs"="_bbf xargs"
alias "xz"="_bbf xz"
alias "xzcat"="_bbf xzcat"
alias "yes"="_bbf yes"
alias "zcat"="_bbf zcat"

alias echo="builtin echo"
alias false="builtin false"
alias printf="builtin printf"
alias pwd="builtin pwd"
alias test="builtin test"
alias true="builtin true"

alias lzmacat="_bbf lzcat"
alias dir="_bbf ls"
alias ll="_bbf ls -l --color=auto"
alias la="_bbf ls -al --color=auto"
alias l="_bbf ls -al --color=auto"
alias newtab="/bin/MobaSendMsg.exe MobaXterm -newtab"
alias Newtab="/bin/MobaSendMsg.exe MobaXterm -newtab"
alias NewTab="/bin/MobaSendMsg.exe MobaXterm -newtab"
alias newTab="/bin/MobaSendMsg.exe MobaXterm -newtab"
alias MobaNewtab="/bin/MobaSendMsg.exe MobaXterm -newtab"
alias new="/bin/MobaSendMsg.exe MobaXterm -newtab"
alias tab="/bin/MobaSendMsg.exe MobaXterm -newtab"

alias MobaControlAccessibility="/bin/MobaControlPanel MobaControlAccessibility"
alias MobaControlAdminTools="/bin/MobaControlPanel MobaControlAdminTools"
alias MobaControlAudio="/bin/MobaControlPanel MobaControlAudio"
alias MobaControlAudioVolume="/bin/MobaControlPanel MobaControlAudioVolume"
alias MobaControlCertificates="/bin/MobaControlPanel MobaControlCertificates"
alias MobaControlCheckDisks="/bin/MobaControlPanel MobaControlCheckDisks"
alias MobaControlCheckSystemFiles="/bin/MobaControlPanel MobaControlCheckSystemFiles"
alias MobaControlClean="/bin/MobaControlPanel MobaControlClean"
alias MobaControlColors="/bin/MobaControlPanel MobaControlColors"
alias MobaControlComputer="/bin/MobaControlPanel MobaControlComputer"
alias MobaControlDCom="/bin/MobaControlPanel MobaControlDCom"
alias MobaControlDefrag="/bin/MobaControlPanel MobaControlDefrag"
alias MobaControlDevices="/bin/MobaControlPanel MobaControlDevices"
alias MobaControlDirectX="/bin/MobaControlPanel MobaControlDirectX"
alias MobaControlDisks="/bin/MobaControlPanel MobaControlDisks"
alias MobaControlDisplay="/bin/MobaControlPanel MobaControlDisplay"
alias MobaControlDriversList="/bin/MobaControlPanel MobaControlDriversList"
alias MobaControlEvents="/bin/MobaControlPanel MobaControlEvents"
alias MobaControlFirewall="/bin/MobaControlPanel MobaControlFirewall"
alias MobaControlFolders="/bin/MobaControlPanel MobaControlFolders"
alias MobaControlFonts="/bin/MobaControlPanel MobaControlFonts"
alias MobaControlInternational="/bin/MobaControlPanel MobaControlInternational"
alias MobaControlInternet="/bin/MobaControlPanel MobaControlInternet"
alias MobaControlKeyboard="/bin/MobaControlPanel MobaControlKeyboard"
alias MobaControlMouse="/bin/MobaControlPanel MobaControlMouse"
alias MobaControlNetwork="/bin/MobaControlPanel MobaControlNetwork"
alias MobaControlNewDevice="/bin/MobaControlPanel MobaControlNewDevice"
alias MobaControlOdbc="/bin/MobaControlPanel MobaControlOdbc"
alias MobaControlPanel="/bin/MobaControlPanel"
alias MobaControlPerformances="/bin/MobaControlPanel MobaControlPerformances"
alias MobaControlPolicies="/bin/MobaControlPanel MobaControlPolicies"
alias MobaControlPrinters="/bin/MobaControlPanel MobaControlPrinters"
alias MobaControlPrograms="/bin/MobaControlPanel MobaControlPrograms"
alias MobaControlRegistry="/bin/MobaControlPanel MobaControlRegistry"
alias MobaControlRestore="/bin/MobaControlPanel MobaControlRestore"
alias MobaControlScheduler="/bin/MobaControlPanel MobaControlScheduler"
alias MobaControlSecurity="/bin/MobaControlPanel MobaControlSecurity"
alias MobaControlServices="/bin/MobaControlPanel MobaControlServices"
alias MobaControlShares="/bin/MobaControlPanel MobaControlShares"
alias MobaControlSignature="/bin/MobaControlPanel MobaControlSignature"
alias MobaControlStartup="/bin/MobaControlPanel MobaControlStartup"
alias MobaControlSystem="/bin/MobaControlPanel MobaControlSystem"
alias MobaControlSystemFiles="/bin/MobaControlPanel MobaControlSystemFiles"
alias MobaControlTasks="/bin/MobaControlPanel MobaControlTasks"
alias MobaControlTelephony="/bin/MobaControlPanel MobaControlTelephony"
alias MobaControlTime="/bin/MobaControlPanel MobaControlTime"
alias MobaControlUpdates="/bin/MobaControlPanel MobaControlUpdates"
alias MobaControlUsers="/bin/MobaControlPanel MobaControlUsers"
alias MobaControlUsersAdvanced="/bin/MobaControlPanel MobaControlUsersAdvanced"
alias MobaControlWindowsVersion="/bin/MobaControlPanel MobaControlWindowsVersion"
alias MobaProcessInfo="/bin/top"
alias htop="/bin/top"
alias MobaProcessInfoNoColor="/bin/top -nocolor"
alias MobaHwInfo="/bin/MobaHwInfo"
alias MobaKillTask="/bin/MobaKillTask"
alias MobaSwInfo="/bin/MobaSwInfo"
alias MobaTaskList="/bin/top"
alias MobApt="/bin/MobApt"
alias Mobapt="/bin/MobApt"
alias mobaprocessinfo="/bin/top"
alias mobaprocessinfonocolor="/bin/top -nocolor"
alias mobahwinfo="/bin/MobaHwInfo"
alias mobakilltask="/bin/MobaKillTask"
alias mobaswinfo="/bin/MobaSwInfo"
alias mobatasklist="/bin/top"
alias mobapt="/bin/MobApt"
alias top="/bin/top"
alias top-nocolor="/bin/top -nocolor"
alias ps2="/bin/top -once"
alias ps2-nocolor="/bin/top -once -nocolor"
alias XWin="/bin/XWin.exe"
alias xwin="/bin/XWin.exe"
alias apt-cyg="/bin/apt-cyg"
alias apt-get="/bin/MobaBox.exe apt-get"
alias ascii="/bin/ascii"
alias autossh="/bin/autossh.exe"
alias balance="/bin/balance.exe -M"
alias bc="/bin/bc.exe"
alias beep="/bin/beep.exe"
alias cfourcc="/bin/cfourcc.exe"
alias connect="/bin/connect.exe"
alias connect-proxy="/bin/connect.exe"
alias proxy-connect="/bin/connect.exe"
alias ctris="/bin/ctris.exe"
alias curl="/bin/curl.exe"
alias git="/bin/git.exe"
alias ninvaders="/bin/ninvaders.exe"
alias greed="/bin/greed.exe"
alias cygpath="/bin/cygpath.exe"
alias cygstart="/bin/cygstart.exe"
alias editrights="/bin/editrights.exe"
alias extract_compressed_fs="/bin/extract_compressed_fs.exe"
alias fdupes="/bin/fdupes.exe"
alias fortune="/bin/fortune"
alias ftp="/bin/ftp.exe"
alias getfacl="/bin/getfacl.exe"
alias glxgears="/bin/glxgears.exe"
alias glxinfo="/bin/glxinfo.exe"
alias Rainbowizer="/bin/Rainbowizer"
alias grep="/bin/grep.exe --colour"
alias grep.exe="/bin/grep.exe --colour"
alias egrep="/bin/grep.exe --colour -E"
alias fgrep="/bin/grep.exe --colour -F"
alias fvwm="/bin/fvwm"
alias rgrep="/bin/grep.exe --colour -r"
alias httping="/bin/httping.exe"
alias iconv="/bin/iconv.exe"
alias iperf="/bin/iperf.exe"
alias iperf2="/bin/iperf.exe"
alias iperf3="/bin/iperf3.exe"
alias launch="/bin/cygstart.exe"
alias ldd="/bin/ldd.exe"
alias makeself="/bin/makeself.sh"
alias makeself.sh="/bin/makeself.sh"
alias man="/bin/man"
alias mathomatic="/bin/mathomatic.exe"
alias mkgroup="/bin/mkgroup.exe"
alias mkpasswd="/bin/mkpasswd.exe"
alias mkshortcut="/bin/mkshortcut.exe"
alias socat="/bin/socat.exe"
alias soliterm="/bin/soliterm.exe"
alias Soliterm="/bin/soliterm.exe"
alias termwalk="/bin/termwalk.exe"
alias Termwalk="/bin/termwalk.exe"
alias mount="/bin/mount.exe"
alias ncdu="/bin/ncdu.exe"
alias ncftp="/bin/ftp.exe"
alias nimesweeper="/bin/nimesweeper.exe"
alias nc="/bin/nc.exe"
alias open="/bin/cygstart.exe"
alias passwd="/bin/passwd.exe"
alias paste="/bin/paste.exe"
alias png2ico="/bin/png2ico"
alias rcp="/bin/rcp.exe"
alias regtool="/bin/regtool.exe"
alias rsync="/bin/rsync.exe"
alias run="/bin/cygstart.exe"
alias setfacl="/bin/setfacl.exe"
alias setx11dpi="/bin/setx11dpi"
alias x11setdpi="/bin/setx11dpi"
alias xsetdpi="/bin/setx11dpi"
alias setxkbmap='/bin/setxkbmap.exe -I "`/bin/cygpath.exe -w "/usr/share/X11/xkb/"`"'
alias sh="/bin/bash.exe"
alias showkey="/bin/showkey.exe"
alias shutdown="/bin/shutdown.exe"
alias sshpass="/bin/sshpass.exe"
alias ssh-add="/bin/ssh-add.exe"
alias ssh-agent="/bin/ssh-agent.exe"
alias ssh-pkcs11-helper="/bin/ssh-pkcs11-helper.exe"
alias ssh-copy-id="/bin/ssh-copy-id"
alias strace="/bin/strace.exe"
alias sudo="/bin/cygstart.exe --action=runas"
alias sudoku="/bin/sudoku.exe"
alias umount="/bin/umount.exe"
alias vi="/bin/vim.exe"
alias vim="/bin/vim.exe"
alias waitforX="/bin/waitforX"
alias wget="/bin/wget.exe"
alias whois="/bin/whois"
alias xauth="/bin/xauth.exe"
alias xdpyinfo="/bin/xdpyinfo.exe"
alias xev="/bin/xev.exe"
alias xkbevd="/bin/xkbevd.exe"
alias xkill="/bin/xkill.exe"
alias xlsatoms="/bin/xlsatoms.exe"
alias xlsclients="/bin/xlsclients.exe"
alias xlsfonts="/bin/xlsfonts.exe"
alias xkbcomp="/bin/xkbcomp.exe"
alias xmodmap="/bin/xmodmap.exe"
alias xhost="/bin/xhost.exe"
alias xprop="/bin/xprop.exe"
alias xrdb="/bin/xrdb.exe"
alias kinit="/bin/kinit.exe"
alias klist="/bin/klist.exe"
alias lrz="/bin/lrz.exe"
alias lsz="/bin/lsz.exe"
alias rz="/bin/lrz.exe --zmodem"
alias sz="/bin/lsz.exe --zmodem"
alias rx="/bin/lrz.exe --xmodem"
alias sx="/bin/lsz.exe --xmodem"
alias rb="/bin/lrz.exe --ymodem"
alias sb="/bin/lsz.exe --ymodem"
alias minicom="/bin/minicom.exe -m -c on"
alias xminicom="/bin/minicom.exe -m -c on"
alias ascii-xfr="/bin/ascii-xfr.exe"
alias runscript="/bin/runscript.exe"



alias MobaWMIRequest="/bin/MobaBox.exe wmirequest"
alias WMIRequest="/bin/MobaBox.exe wmirequest"
alias mobawmirequest="/bin/MobaBox.exe wmirequest"
alias wmirequest="/bin/MobaBox.exe wmirequest"
alias MobaListOpenPorts="/bin/MobaListPorts"
alias Mobalistopenports="/bin/MobaListPorts"
alias mobalistopenports="/bin/MobaListPorts"
alias ListOpenPorts="/bin/MobaListPorts"
alias listopenports="/bin/MobaListPorts"
alias PortsInfo="/bin/MobaListPorts"
alias NetworkPortsList="/bin/MobaListPorts"
alias MobaPictureViewer="/bin/MobaPictureViewer"
alias Mobapictureviewer="/bin/MobaPictureViewer"
alias mobapictureviewer="/bin/MobaPictureViewer"
alias ShowImage="/bin/MobaPictureViewer"
alias showimage="/bin/MobaPictureViewer"
alias DisplayImage="/bin/MobaPictureViewer"
alias OpenImage="/bin/MobaPictureViewer"
alias openimage="/bin/MobaPictureViewer"
alias ViewImage="/bin/MobaPictureViewer"
alias viewimage="/bin/MobaPictureViewer"
alias PictureView="/bin/MobaPictureViewer"
alias pictureview="/bin/MobaPictureViewer"
alias PhotoView="/bin/MobaPictureViewer"
alias ImageView="/bin/MobaPictureViewer"
alias imageview="/bin/MobaPictureViewer"
alias Show="/bin/MobaPictureViewer"
alias Display="/bin/MobaPictureViewer"
alias PicView="/bin/MobaPictureViewer"
alias picview="/bin/MobaPictureViewer"
alias MobaTextEditor="/bin/MobaTextEditor"
alias Mobatexteditor="/bin/MobaTextEditor"
alias mobatexteditor="/bin/MobaTextEditor"
alias TextEdit="/bin/MobaTextEditor"
alias textedit="/bin/MobaTextEditor"
alias Edit="/bin/MobaTextEditor"
alias edit="/bin/MobaTextEditor"
alias OpenText="/bin/MobaTextEditor"
alias opentext="/bin/MobaTextEditor"
alias DiffFiles="/bin/MobaCompareFiles"
alias difffiles="/bin/MobaCompareFiles"
alias MobaDiffFiles="/bin/MobaCompareFiles"
alias Mobadifffiles="/bin/MobaCompareFiles"
alias mobadifffiles="/bin/MobaCompareFiles"
alias CompareFiles="/bin/MobaCompareFiles"
alias FilesDiff="/bin/MobaCompareFiles"
alias filesdiff="/bin/MobaCompareFiles"
alias FilesCompare="/bin/MobaCompareFiles"
alias TextDiff="/bin/MobaCompareFiles"
alias Textdiff="/bin/MobaCompareFiles"
alias textdiff="/bin/MobaCompareFiles"
alias MobaTextDiff="/bin/MobaCompareFiles"
alias Mobatextdiff="/bin/MobaCompareFiles"
alias mobatextdiff="/bin/MobaCompareFiles"
alias DiffFolders="/bin/MobaCompareFolders"
alias difffolders="/bin/MobaCompareFolders"
alias MobaDiffFolders="/bin/MobaCompareFolders"
alias Mobadifffolders="/bin/MobaCompareFolders"
alias mobadifffolders="/bin/MobaCompareFolders"
alias MobaFoldersDiff="/bin/MobaCompareFolders"
alias mobafoldersdiff="/bin/MobaCompareFolders"
alias CompareFolders="/bin/MobaCompareFolders"
alias comparefolders="/bin/MobaCompareFolders"
alias FoldersDiff="/bin/MobaCompareFolders"
alias foldersdiff="/bin/MobaCompareFolders"
alias FoldersCompare="/bin/MobaCompareFolders"
alias DirectoriesCompare="/bin/MobaCompareFolders"
alias winpty="/bin/conin.exe"
alias winpty.exe="/bin/conin.exe"
alias cmd="/bin/conin.exe cmd"
alias cmd.exe="/bin/conin.exe cmd"
alias ps="/bin/ps.exe -W"
alias ps.exe="/bin/ps.exe -W"
alias ifconfig="/bin/MobaBox.exe ifconfig"
alias kill="/bin/kill.exe -f"
alias killX="/bin/killX"
alias kill.exe="/bin/kill.exe -f"
alias reboot="/bin/shutdown.exe -f -r now"
alias halt="/bin/shutdown.exe -f -s now"
alias help="/bin/help"
alias about="open https://mobaxterm.mobatek.net/download.html"
alias telnetd="/etc/init.d/telnetd"
alias ftpd="/etc/init.d/ftpd"
alias lscolors="/bin/lscolors"
alias mintty="export PROMPT_TYPE=rxvt; [ -e /bin/mintty.exe ] && /bin/mintty.exe bash -l -i || rxvt"
alias xterm="export PROMPT_TYPE=rxvt; [ -e /bin/xterm.exe ] && /bin/xterm.exe bash -l -i || rxvt"
alias rxvt="PROMPT_TYPE=rxvt rxvt"

function _use_apt {
  echo -e "\e[31m$1\e[0m is not available here, but you can use \e[32mapt-get\e[0m instead."
}
alias yum="_use_apt yum"
alias urpmi="_use_apt urpmi"
alias zypper="_use_apt zypper"
alias emerge="_use_apt emerge"

function echo2 {
  builtin echo -e "\e#3$@\n\e#4$@"
}

function cat2 {
  if [ "$1" = "" ]; then
    while read i; do echo2 "$i"; done
  else
    cat "$1" | (while read i; do echo2 "$i"; done)
  fi
}

function microcom {
  [ "$1" == "-s" ] && COMPORT=" on \033[36m$3\033[0m" || COMPORT="\033[0m"
  echo -e "\033[31mLaunching microcom serial connection$COMPORT.\n\033[31mPress Ctrl+X to exit.\033[0m"
  /bin/busybox.exe microcom "$@"
}

function ssh-keygen {
  [ -e "/home/mobaxterm/README.txt" ] && cat "/home/mobaxterm/README.txt"
  /bin/ssh-keygen.exe "$@"
}

function zless {
  /bin/busybox.exe gunzip -c "$@" | less
}

function vless {
  /bin/vim.exe -R -u /etc/vimrc.less -c 'set nomod nolist' "$@"
}

function less-syntax {
  /bin/vim.exe -R -u /etc/vimrc.less -c 'set nomod nolist' "$@"
}

function view {
  /bin/vim.exe -R -u /etc/vimrc.less -c 'set nomod nolist' "$@"
}

function services-status {
  for i in `ls /etc/init.d/`; do /etc/init.d/$i status; done
}

function zmore {
  /bin/busybox.exe gunzip -c "$@" | more
}

function bzless {
  /bin/busybox.exe bunzip2 -c "$@" | less
}

function bzmore {
  /bin/busybox.exe bunzip2 -c "$@" | more
}

alias ssh="/bin/ssh.exe"
alias  "ssh-nocompression"="/bin/ssh.exe -o Compression=no"
alias  "ssh-noencryption"="/bin/ssh.exe -o UseRsh=yes"
alias scp="([ -n "${KRB5_CONFIG}" ] && [ -e "${KRB5_CONFIG}" ] && /bin/scp.exe -S /bin/_kssh.exe -o GSSAPIAuthentication=yes -o GSSAPIDelegateCredentials=yes) || /bin/scp.exe -S /bin/_ssh.exe"
alias sftp="([ -n "${KRB5_CONFIG}" ] && [ -e "${KRB5_CONFIG}" ] && /bin/sftp.exe -S /bin/_kssh.exe -o GSSAPIAuthentication=yes -o GSSAPIDelegateCredentials=yes) || /bin/sftp.exe -S /bin/_ssh.exe"

function telnet {
  echo -ne "\0033]2;$@\a"
  /bin/telnet.exe "$@"
}

function rsh {
  echo -ne "\0033]2;$@\a"
  /bin/rsh.exe "$@"
}

function rlogin {
  echo -ne "\0033]2;$1\a"
  /bin/rlogin.exe "$@"
}

function mcedit {
  /bin/mc.exe --edit=$@
}

function service {
  if [ -z "$1" ]; then
    services-status
  else
    /etc/init.d/"$@"
  fi
}

function dosconvert() {
  CP1="`cat /proc/registry/HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Control/Nls/CodePage/OEMCP`"
  CP2="${LANG##*.}"
  if iconv -l | grep -q "CP$CP1" >/dev/null 2>/dev/null && iconv -l | grep -q "$CP2" >/dev/null 2>/dev/null; then
    "$@" | iconv -s -c -t $CP2 -f CP$CP1
  else
    "$@"
  fi
}

alias ping="dosconvert ping.exe"
alias ipconfig="dosconvert ipconfig.exe"
alias tracert="dosconvert tracert.exe"
alias netstat="dosconvert netstat.exe"
alias route="dosconvert route.exe"
alias arp="dosconvert arp.exe"
alias nbtstat="dosconvert nbtstat.exe"
alias netsh="dosconvert netsh.exe"



function ToolDisabled {
  echo -e "\e[31mSorry: $1 has been disabled by your System Administrator.\e[0m"
  echo
}
function ToolNotIncluded {
  if ls "/bin/$1" >/dev/null 2>/dev/null || ls "/bin/$1.exe" >/dev/null 2>/dev/null; then
    progname="$1"
    unalias "$progname"
    shift
    if [ "$1" == "-si" ] && [ -n "$2" ]; then
      shift
      shift
    fi
    "$progname" "$@"
  else
    command_not_found_handle "$1"
    if [ "$?" != "0" ]; then
      if [ "$2" == "-si" ] && [ -n "$3" ]; then
        builtin echo
        builtin echo -e "Starting \033[32m$3\033[0m instead..."
        NEWOPTS=("$@")
        unset NEWOPTS[0]
        unset NEWOPTS[1]
        unset NEWOPTS[2]
        if [ "$3" == "TCPCapture" ]; then
          /bin/MobaBox.exe mobasendmsg MobaXterm tcpcapture
        else
          $3 "${NEWOPTS[@]}"
        fi
        unset NEWOPTS
      fi
    fi
  fi
}

function _search_in_winpath(){
  if builtin echo "$WINPATH" | /bin/busybox.exe grep -q -i "$1"; then
    builtin echo "$WINPATH" | /bin/busybox.exe sed -e "s/;/\n/g" -e "s|\\\\|/|g" | (while read i; do if [ -e "$i/$2" ] || [ -e "$i/$2.exe" ]; then [ -e "$i/cygwin1.dll" ] || echo "$i/$2"; fi; done) | head -1
  fi
}

function _exec_cyg_or_win_binary() {
  MyWinBin="`which $1`"
  if [ "$MyWinBin" = "" ]; then
    MyWinBin="`_search_in_winpath "$2" "$1"`"
  fi 
  if [ "$MyWinBin" = "" ]; then
    ToolNotIncluded "$1"
  else
    shift
    shift
    MyWinBinTrunked1="${MyWinBin#*/}"
    MyWinBinTrunked2="${MyWinBin#*/*/}"
    if [ "${MyWinBin%%/*}" = "C:" ] || [ "${MyWinBin%%/*}" = "c:" ] || [ "${MyWinBinTrunked1%%/*}" = "drives" ] || [ "${MyWinBinTrunked2%%/*}" = "c" ]; then
      /bin/conin.exe "$MyWinBin" "$@"
    else
      "$MyWinBin" "$@"
    fi
  fi
}

alias powershell="_exec_cyg_or_win_binary powershell powershell"
alias pwsh="_exec_cyg_or_win_binary pwsh pwsh"
alias javac="_exec_cyg_or_win_binary javac java"
alias java="_exec_cyg_or_win_binary java java"
alias python="_exec_cyg_or_win_binary python python"
alias python3="_exec_cyg_or_win_binary python3 python3"
alias mysql="_exec_cyg_or_win_binary mysql sql"
alias psql="_exec_cyg_or_win_binary psql sql"
alias kubectl="_exec_cyg_or_win_binary kubectl kubectl"

function docker() {
  MyDocker="`which docker`"
  if [ "$MyDocker" != "" ]; then
    MyDocker="docker.exe"
  else
    if [ -e "`cat /proc/registry*/HKEY_LOCAL_MACHINE/SOFTWARE/Docker*/*/*/BinPath`/docker.exe" ]; then
      MyDocker="`cat /proc/registry*/HKEY_LOCAL_MACHINE/SOFTWARE/Docker*/*/*/BinPath`/docker.exe"
    elif [ -e "`cat /proc/registry*/HKEY_LOCAL_MACHINE/SOFTWARE/Docker*/*/*/AppPath`/docker.exe" ]; then
      MyDocker="`cat /proc/registry*/HKEY_LOCAL_MACHINE/SOFTWARE/Docker*/*/*/AppPath`/docker.exe"
    elif [ -e "`cat /proc/registry*/HKEY_LOCAL_MACHINE/SOFTWARE/Docker*/*/*/AppPath`/resources/bin/docker.exe" ]; then
      MyDocker="`cat /proc/registry*/HKEY_LOCAL_MACHINE/SOFTWARE/Docker*/*/*/AppPath`/resources/bin/docker.exe"
    else
      MyDocker="`_search_in_winpath docker docker.exe`"
    fi
  fi 
  if [ "$MyDocker" = "" ]; then
    builtin echo "Sorry, docker does not seem to be installed"
  else
    if [ "$1" = "run" ]; then
      shift
      /bin/conin.exe "$MyDocker" run -e DISPLAY=$EXPORTED_DISPLAY "$@"
    elif [ "$1" = "images" ] || [ "$1" = "ps" ]; then
      "$MyDocker" "$@"
    else
      /bin/conin.exe "$MyDocker" "$@"
    fi
  fi
}

alias nedit="ToolNotIncluded nedit -si MobaTextEditor"
alias mc="ToolNotIncluded mc"
alias gvim="ToolNotIncluded gvim -si MobaTextEditor"
alias emacs="ToolNotIncluded emacs -si MobaTextEditor"
alias emacs-w32="ToolNotIncluded emacs-w32 -si MobaTextEditor"
alias xemacs="ToolNotIncluded xemacs -si MobaTextEditor"
alias kate="ToolNotIncluded kate -si MobaTextEditor"
alias kwrite="ToolNotIncluded kwrite -si MobaTextEditor"
alias gedit="ToolNotIncluded gedit -si MobaTextEditor"
alias kdiff="ToolNotIncluded kdiff -si MobaCompareFiles"
alias gphoto="ToolNotIncluded gphoto -si MobaPictureViewer"
alias kuickshow="ToolNotIncluded kuickshow -si MobaPictureViewer"
alias showimg="ToolNotIncluded showimg -si MobaPictureViewer"
alias perl="ToolNotIncluded perl"
alias lua="ToolNotIncluded lua"
alias ruby="ToolNotIncluded ruby"
alias texmacs="ToolNotIncluded texmacs"
alias lyx="ToolNotIncluded lyx"
alias tex="ToolNotIncluded teX"
alias latex="ToolNotIncluded latex"
alias make="ToolNotIncluded make"
alias gcc="ToolNotIncluded gcc"
alias g++="ToolNotIncluded g++"
alias g77="ToolNotIncluded g77"
alias gpc="ToolNotIncluded gpc"
alias gcj="ToolNotIncluded gcj"
alias konqueror="ToolNotIncluded konqueror"
alias nautilus="ToolNotIncluded nautilus"
alias pcmanfm="ToolNotIncluded pcmanfm"
alias zsh="ToolNotIncluded zsh"
alias ksh="ToolNotIncluded ksh"
alias xclock="ToolNotIncluded xclock"
alias xeyes="ToolNotIncluded xeyes"
alias afio="ToolNotIncluded afio -si cpio"
alias zip="ToolNotIncluded zip"
alias cdrecord="ToolNotIncluded cdrecord"
alias autoconf="ToolNotIncluded autoconf"
alias automake="ToolNotIncluded automake"
alias strip="ToolNotIncluded strip"
alias cvs="ToolNotIncluded cvs"
alias svn="ToolNotIncluded svn"
alias ddd="ToolNotIncluded ddd"
alias gdb="ToolNotIncluded gdb"
alias nasm="ToolNotIncluded nasm"
alias hexedit="ToolNotIncluded hexedit"
alias screen="ToolNotIncluded screen"
alias convert="ToolNotIncluded convert"
alias display="ToolNotIncluded display"
alias gv="ToolNotIncluded gv"
alias gs="ToolNotIncluded gs"
alias ghostscript="ToolNotIncluded ghostscript"
alias ploticus="ToolNotIncluded ploticus"
alias plotutils="ToolNotIncluded plotutils"
alias grace="ToolNotIncluded grace"
alias xfig="ToolNotIncluded xfig"
alias expect="ToolNotIncluded expect"
alias email="ToolNotIncluded email"
alias octave="ToolNotIncluded octave"
alias orpie="ToolNotIncluded orpie"
alias singular="ToolNotIncluded singular"
alias ctorrent="ToolNotIncluded ctorrent"
alias geoip="ToolNotIncluded geoip"
alias httptunnel="ToolNotIncluded httptunnel"
alias lftp="ToolNotIncluded lftp"
alias zsync="ToolNotIncluded zsync"
alias pdftk="ToolNotIncluded pdftk"
alias tetex="ToolNotIncluded tetex"
alias aspell="ToolNotIncluded aspell"
alias a2ps="ToolNotIncluded a2ps"
alias multitail="ToolNotIncluded multitail -si tail"
alias file="ToolNotIncluded file"
alias wput="ToolNotIncluded wput"
alias lynx="ToolNotIncluded lynx"
alias links="ToolNotIncluded links"
alias TCPCapture="/bin/MobaBox.exe mobasendmsg MobaXterm tcpcapture"
alias tcpcapture="/bin/MobaBox.exe mobasendmsg MobaXterm tcpcapture"
alias MobaTCPCapture="/bin/MobaBox.exe mobasendmsg MobaXterm tcpcapture"
alias mobatcpcapture="/bin/MobaBox.exe mobasendmsg MobaXterm tcpcapture"
alias tcpdump="ToolNotIncluded tcpdump -si TCPCapture"
alias wireshark="ToolNotIncluded wireshark -si TCPCapture"
alias ethereal="ToolNotIncluded ethereal -si TCPCapture"
alias xcalc="ToolNotIncluded xcalc -si calc"
alias gcalc="ToolNotIncluded gcalc -si calc"
alias kcalc="ToolNotIncluded kcalc -si calc"


alias path='echo $PATH'
alias cgrep='grep --color=always'
alias lsd='ls -d */'
alias lll='ls -la | less'
alias md='mkdir'
alias ..='cd ..'
alias ...='cd ../..'
alias path='echo -e ${PATH//:/\\n}'
alias removeemptylines="sed -i -e '/^$/d'"
alias tree="find . | sed 's/[^/]*\//|   /g;s/| *\([^| ]\)/+--- \1/'"
alias clr="clear; pwd; ls -lrth"
alias title="xtitle"
alias settitle="xtitle"
alias settabtitle="xtitle"
alias tabtitle="xtitle"
function cl { cd $* && ls; }
function xtitle { builtin echo -en  "\e]0;$*\a"; }
function extract() {
  if [ -z "$1" ]; then
    echo "Usage: extract <archive_to_extract>"
  elif [ -f $1 ]; then
    case $1 in
      *.tar.bz2)   tar -xvjf $1;;
      *.tar.gz)    tar -xvzf $1;;
      *.tar.xz)    tar -xvJf $1;;
      *.bz2)       bunzip2 $1;;
      *.gz)        gunzip $1;;
      *.xz)        unxz $1;;
      *.lzma)      unlzma $1;;
      *.tar)       tar -xvf $1;;
      *.tbz2)      tar -xvjf $1;;
      *.tgz)       tar -xvzf $1;;
      *.txz)       tar -xvJf $1;;
      *.zip)       unzip $1;;
      *.Z)         uncompress $1;;
      *)           echo "'$1' cannot be extracted via >extract<";;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

function command_not_found_handle() {
  >&2 builtin echo "$1: command not found"
  if shopt -q login_shell 2>/dev/null >/dev/null; then
    if [ -t 1 ] && [ -t 2 ]; then
      MyProg="$1"
      MyProg="${MyProg/\.exe/}"
      MyProg="${MyProg##*/}"
      MyProg="${MyProg//+/\\+}"
      if /bin/busybox.exe grep -q -E "^${MyProg}$" /etc/setup/cmdlist 2>/dev/null; then
        AptPack=""
        [ ! -e "/etc/setup/setup.moba.ini" ] && (cd /etc/setup && /bin/MobaBox.exe wget http://download.mobatek.net/mobasetup.32.2.ini setup.moba.ini) 2>/dev/null >/dev/null
        if [ -e "/etc/setup/setup.moba.ini" ]; then
          AptPack="`/bin/busybox.exe grep -E "^@ ${MyProg}[ $]" /etc/setup/setup.moba.ini | /bin/busybox.exe tail -1 | /bin/busybox.exe sed -e "s/@ //g"`"
          [ "$AptPack" = "" ] && AptPack="`/bin/busybox.exe grep -E -B5 "^cmd:.* ${MyProg}[ $]" /etc/setup/setup.moba.ini | /bin/busybox.exe grep -E "^@ " | /bin/busybox.exe tail -1 | /bin/busybox.exe sed -e "s/@ //g"`"
          if [ "$AptPack" != "" ]; then
            builtin echo
            builtin echo -e "\e[1;34m\xEE\x83\xB8 $1\e[0m can be installed using the following command: \e[1;35mapt-get install $AptPack\e[0m"
            builtin echo
            return 0
          fi
        fi
      fi
    fi
  fi
  return 1
}

if [ ! -e "/etc/ssh_agent_env.sh" ]; then
  _tob ls -al /bin/ssh-agent.exe >/dev/null 2>/dev/null
  if [ -e "/bin/ssh-agent.exe" ]; then
    /bin/ssh-agent.exe > /etc/ssh_agent_env.sh
    _tob chmod 777 /etc/ssh_agent_env.sh
    . /etc/ssh_agent_env.sh >/dev/null 2>&1
  fi
else
  . /etc/ssh_agent_env.sh >/dev/null 2>&1
fi
